version: 2

updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"

groups:
    production-dependencies:
        dependency-type: "production"
    development-dependencies:
        dependency-type: "development"
